apiVersion: apps/v1
kind: Deployment
metadata:
  name: panoptes-jet
  labels:
    app: panoptes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: panoptes
  template:
    metadata:
      labels:
        app: panoptes
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: panoptes-jet
        image: uberkube00.slaq.org:5000/slaqworx/panoptes-jet:amd64
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JAVA_TOOL_OPTIONS
          value: "-Xms6560m -Xmx6560m -Djava.rmi.server.hostname=$(HOST_IP) -XX:ActiveProcessorCount=4"
        ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 8090
          hostPort: 8090
        - containerPort: 8000
          hostPort: 8000
        - containerPort: 5701
          hostPort: 5701
