apiVersion: apps/v1
kind: Deployment
metadata:
  name: panoptes
  labels:
    app: panoptes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: panoptes
  template:
    metadata:
      labels:
        app: panoptes
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - uberkube01
      containers:
      - name: panoptes
        image: uberkube01.slaq.org:5000/slaqworx/panoptes:arm64
        imagePullPolicy: Always
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JAVA_TOOL_OPTIONS
          # number of CPUs isn't detected properly on Odroid N2
          value: "-Djava.rmi.server.hostname=$(HOST_IP) -XX:ActiveProcessorCount=6"
        ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 8090
          hostPort: 8090
        - containerPort: 8000
          hostPort: 8000
        - containerPort: 5701
          hostPort: 5701
