{
 "title": "Panoptes Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Records Ingest",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "records in/sec" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"Source:_benchmarkSource\"})",
     "legendFormat": "benchmarks"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"Source:_portfolioSource\"})",
     "legendFormat": "portfolios"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"Source:_securitySource\"})",
     "legendFormat": "securities"
    }
   ]
  },
  {
   "title": "Processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "records out/sec" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"benchmarkEvaluator\"})",
     "legendFormat": "benchmark evaluator"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"portfolioEvaluator\"})",
     "legendFormat": "portfolio evaluator"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsOutPerSecond{operator_name=\"benchmarkComparator\"})",
     "legendFormat": "benchmark comparator"
    }
   ]
  },
  {
   "title": "Records Egress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "records out/sec" }
   ],
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_numRecordsInPerSecond{operator_name=\"Sink:_evaluationResultSink\"})",
     "legendFormat": "results"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "cpu %" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "heap used, bytes" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}